/* Hunter System — exercise library.
   Each entry: n name · m muscles · eq equipment · fig animation key · steps how to do it ·
   x common mistakes · b breathing · alt easier/harder option. */
window.EX = {
 /* ---------------- LEGS ---------------- */
 legpress:{n:'Leg press',m:'Quads · glutes · hamstrings',eq:'Leg press machine',fig:'legpress',
  steps:['Sit with your back and hips flat on the pad.','Place feet shoulder-width apart in the middle of the platform, toes slightly out.','Release the safety handles and lower the platform until your knees reach about 90°.','Push through your whole foot, mostly the heels, until legs are almost straight.'],
  x:['Locking the knees hard at the top','Letting the lower back roll off the pad at the bottom','Knees caving inward'],b:'Breathe in as you lower, out as you push.',alt:'Easier: shorter range. Harder: pause 2 s at the bottom.'},
 boxsquat:{n:'Box squat',m:'Quads · glutes',eq:'Bench or box',fig:'boxsquat',
  steps:['Stand in front of a bench, feet shoulder-width apart.','Reach your arms forward for balance.','Push your hips back and sit down slowly until you lightly touch the bench.','Without relaxing, push the floor away and stand up tall.'],
  x:['Dropping onto the bench','Heels lifting off the floor','Rounding the back'],b:'In on the way down, out on the way up.',alt:'Harder: hold a dumbbell at your chest.'},
 airsquat:{n:'Bodyweight squat',m:'Quads · glutes',eq:'None',fig:'airsquat',
  steps:['Feet shoulder-width, toes slightly out.','Arms forward, chest up.','Sit down between your heels as low as you can with a flat back.','Stand up by driving through your mid-foot.'],
  x:['Knees caving in','Heels lifting','Bending forward too much'],b:'In going down, out coming up.',alt:'Easier: squat to a chair. Harder: jump squat.'},
 goblet:{n:'Goblet squat',m:'Quads · glutes · core',eq:'Dumbbell or kettlebell',fig:'goblet',
  steps:['Hold one dumbbell vertically against your chest with both hands.','Feet slightly wider than shoulders, toes out.','Sit down between your heels, elbows travelling inside your knees.','Keep the chest up and stand back up.'],
  x:['Letting the dumbbell pull you forward','Not going deep enough','Knees caving in'],b:'In going down, out coming up.',alt:'Harder: heavier dumbbell or 3 s lowering.'},
 squat:{n:'Barbell back squat',m:'Quads · glutes · core',eq:'Barbell + squat rack',fig:'squat',
  steps:['Set the bar at chest height in the rack. Step under it so it rests on your upper back, not your neck.','Grip the bar just outside shoulders, squeeze shoulder blades, step back 2 small steps.','Brace your stomach like someone is about to punch it.','Sit down between your heels until thighs are at least parallel to the floor.','Drive up, keeping the chest and hips rising together.'],
  x:['Bar on the neck','Knees caving in','Hips shooting up first','Squatting without safety pins set'],b:'Big breath in and hold your brace at the top, go down, breathe out after passing the hardest part.',alt:'Easier: goblet squat. Always set the safety pins just below your bottom position.'},
 rdl:{n:'Romanian deadlift',m:'Hamstrings · glutes · lower back',eq:'Dumbbells or barbell',fig:'rdl',
  steps:['Stand tall holding the weights in front of your thighs.','Unlock your knees slightly and keep them there.','Push your hips straight back, sliding the weights down your legs.','Stop when you feel a strong hamstring stretch, usually just below the knees.','Squeeze your glutes to stand back up.'],
  x:['Rounding the back','Bending the knees into a squat','Letting the weights drift away from the legs'],b:'In as you hinge down, out as you stand.',alt:'Easier: lighter dumbbells. Harder: single-leg version.'},
 deadlift:{n:'Conventional deadlift',m:'Whole back chain · glutes · grip',eq:'Barbell',fig:'deadlift',
  steps:['Stand with the bar over your mid-foot, feet hip-width.','Bend down and grip the bar just outside your legs.','Bring shins to the bar, chest up, back flat, shoulders slightly in front of the bar.','Brace hard and push the floor away. Keep the bar touching your legs.','Lock out by squeezing the glutes. Lower the same path under control.'],
  x:['Rounded lower back','Jerking the bar off the floor','Leaning back at the top','Bar drifting away from the legs'],b:'Breathe in and brace before each rep, out at the top.',alt:'Easier: trap-bar deadlift or RDL. Start light. Form first.'},
 lunge:{n:'Walking lunge',m:'Quads · glutes · balance',eq:'Dumbbells optional',fig:'lunge',
  steps:['Stand tall, dumbbells at your sides.','Take a long step forward.','Lower until the back knee nearly touches the floor.','Push through the front heel and step through into the next lunge.'],
  x:['Short steps that push the knee far past the toes','Leaning forward','Front knee caving in'],b:'In as you lower, out as you step up.',alt:'Easier: static lunge holding a support.'},
 bulgarian:{n:'Bulgarian split squat',m:'Quads · glutes',eq:'Bench + dumbbells',fig:'bulgarian',
  steps:['Stand about 2 feet in front of a bench, back foot laces on the bench.','Hold dumbbells at your sides.','Lower straight down until the front thigh is parallel to the floor.','Drive up through the front heel. Finish all reps, then switch legs.'],
  x:['Front foot too close to the bench','Bouncing off the bottom','Leaning on the back leg'],b:'In going down, out coming up.',alt:'Easier: no weights. The hardest leg move in the plan, so start light.'},
 stepup:{n:'Dumbbell step-up',m:'Quads · glutes',eq:'Box or bench + dumbbells',fig:'stepup',
  steps:['Stand facing a knee-height box, dumbbells at your sides.','Place your whole right foot on the box.','Drive through the right heel to stand on the box. Do not push off the back foot.','Step down slowly. Do all reps on one leg, then switch.'],
  x:['Pushing off the bottom foot','Box too high','Knee caving in'],b:'Out as you step up.',alt:'Easier: lower step, no weights.'},
 hipthrust:{n:'Barbell hip thrust',m:'Glutes · hamstrings',eq:'Bench + barbell with pad',fig:'hipthrust',
  steps:['Sit on the floor with your upper back against a bench, padded bar over your hips.','Feet flat, shoulder-width, knees bent.','Drive through your heels to lift your hips until your body is flat from shoulders to knees.','Squeeze the glutes for 1 second, then lower.'],
  x:['Arching the lower back at the top','Feet too far or too close','Pushing through the toes'],b:'Out as you lift, in as you lower.',alt:'Easier: glute bridge on the floor.'},
 bridge:{n:'Glute bridge',m:'Glutes · core',eq:'Mat',fig:'bridge',
  steps:['Lie on your back, knees bent, feet flat near your hips.','Arms on the floor by your sides.','Push through your heels and lift your hips until body is straight from shoulders to knees.','Squeeze 2 seconds at the top, lower slowly.'],
  x:['Arching the lower back','Pushing through toes'],b:'Out as you lift.',alt:'Harder: single-leg bridge.'},
 legcurl:{n:'Leg curl machine',m:'Hamstrings',eq:'Lying or seated leg curl',fig:'legcurl',
  steps:['Lie face down, knees just off the pad edge, the roller above your heels.','Hold the handles and keep hips pressed down.','Curl your heels toward your hips as far as you can.','Pause, then lower over 3 seconds.'],
  x:['Hips lifting off the pad','Swinging the weight','Fast lowering'],b:'Out as you curl, in as you lower.',alt:'No machine: swiss-ball curls or Nordic negatives.'},
 legext:{n:'Leg extension',m:'Quads',eq:'Leg extension machine',fig:'legext',
  steps:['Sit with your back against the pad, knees at the seat edge.','Roller sits just above your ankles.','Straighten your legs fully and squeeze the quads for 1 second.','Lower slowly.'],
  x:['Kicking the weight up','Lifting hips off the seat'],b:'Out as you extend.',alt:'Use as a finisher with light weight and high reps.'},
 calf:{n:'Standing calf raise',m:'Calves',eq:'Step + dumbbell, or machine',fig:'calf',
  steps:['Stand with the balls of your feet on a step, heels hanging off.','Hold a dumbbell or the rail for balance.','Rise as high as possible onto your toes and pause 1 second.','Lower slowly until heels drop below the step.'],
  x:['Bouncing','Half reps'],b:'Out going up.',alt:'Harder: single-leg.'},
 boxjump:{n:'Box jump',m:'Explosive legs · power',eq:'Sturdy box (knee height to start)',fig:'boxjump',
  steps:['Stand one step from the box, feet hip-width.','Swing your arms back and dip into a quarter squat.','Swing arms forward and jump, landing softly on the whole foot in a half squat.','Stand up on the box, then step down. Never jump down.'],
  x:['Box too high','Landing with straight legs','Jumping down backward'],b:'Short sharp breath out on the jump.',alt:'Easier: squat jumps on the floor.'},
 kbswing:{n:'Kettlebell swing',m:'Glutes · hamstrings · conditioning',eq:'Kettlebell',fig:'kbswing',
  steps:['Feet slightly wider than shoulders, kettlebell a foot in front of you.','Hinge, grip the handle and hike it back between your legs.','Snap your hips forward hard. The bell floats to chest height from hip power, not arms.','Let it fall back, hinging at the hips, and repeat.'],
  x:['Squatting instead of hinging','Lifting with the arms','Rounding the back at the bottom'],b:'Sharp breath out at the top of each swing.',alt:'Start with 12–16 kg.'},
 /* ---------------- CHEST & PUSH ---------------- */
 chestpress:{n:'Chest press machine',m:'Chest · triceps · front shoulders',eq:'Chest press machine',fig:'chestpress',
  steps:['Adjust the seat so the handles line up with mid-chest.','Sit tall with shoulder blades squeezed back.','Press the handles forward until arms are almost straight.','Return slowly until you feel a chest stretch.'],
  x:['Shoulders rolling forward','Locking the elbows','Seat too high or low'],b:'Out as you press.',alt:'Next step: dumbbell bench press.'},
 bench:{n:'Flat dumbbell bench press',m:'Chest · triceps · shoulders',eq:'Flat bench + dumbbells',fig:'bench',
  steps:['Sit with dumbbells on your thighs, lie back and bring them to chest level.','Feet flat, shoulder blades squeezed together.','Press the dumbbells up over your shoulders, bringing them slightly together.','Lower slowly until elbows are just below the bench.'],
  x:['Elbows flared straight out at 90°','Bouncing at the bottom','Feet off the floor'],b:'In lowering, out pressing.',alt:'Easier: chest press machine.'},
 bbbench:{n:'Barbell bench press',m:'Chest · triceps · shoulders',eq:'Bench + barbell + spotter or safety bars',fig:'bbbench',
  steps:['Lie with eyes under the bar, feet flat, shoulder blades pinched.','Grip slightly wider than shoulders.','Unrack and hold the bar over your shoulders.','Lower to the lower chest, elbows about 45° from your body.','Press back up and slightly back over the shoulders.'],
  x:['Bouncing the bar off the chest','Hips lifting off the bench','Training heavy without a spotter or safety bars'],b:'In and brace as you lower, out as you press.',alt:'Easier: dumbbell bench press.'},
 incline:{n:'Incline dumbbell press',m:'Upper chest · shoulders',eq:'Incline bench (30°) + dumbbells',fig:'incline',
  steps:['Set the bench to about 30°.','Kick the dumbbells up to shoulder level.','Press up and slightly together over your upper chest.','Lower slowly to the sides of your upper chest.'],
  x:['Bench too steep (turns into shoulder press)','Arching off the bench'],b:'Out as you press.',alt:'Builds the upper chest that makes the Jin-Woo look.'},
 cablefly:{n:'Cable fly',m:'Chest',eq:'Cable crossover',fig:'cablefly',
  steps:['Set both pulleys high. Grab a handle in each hand and step forward.','Slight bend in the elbows, lean forward a little.','Bring the handles together in front of your chest in a hugging arc.','Return slowly until you feel a stretch.'],
  x:['Turning it into a press by bending the elbows','Going too heavy'],b:'Out as you squeeze together.',alt:'Alternative: pec-deck machine.'},
 pushup:{n:'Push-up',m:'Chest · triceps · core',eq:'None',fig:'pushup',
  steps:['Hands slightly wider than shoulders, body in one straight line.','Squeeze glutes and abs.','Lower until your chest is a fist from the floor, elbows at about 45°.','Push back up to straight arms.'],
  x:['Hips sagging','Head dropping','Half reps'],b:'In going down, out pushing up.',alt:'Easier: hands on a bench, or knees down. Harder: feet elevated.'},
 pikepush:{n:'Pike push-up',m:'Shoulders · triceps',eq:'None',fig:'pikepush',
  steps:['Start in push-up position, then walk your feet in and lift your hips high.','Hands shoulder-width, head between your arms.','Bend the elbows to lower the top of your head toward the floor.','Press back up.'],
  x:['Hips dropping','Elbows flaring wide'],b:'Out pushing up.',alt:'Harder: feet on a bench.'},
 dips:{n:'Parallel bar dips',m:'Chest · triceps',eq:'Dip bars or assisted dip machine',fig:'dips',
  steps:['Grip the bars and jump up to straight arms.','Lean your chest slightly forward, knees bent behind you.','Lower until your shoulders are level with your elbows.','Press back up to straight arms.'],
  x:['Going too deep and straining the shoulders','Swinging','Shrugging the shoulders up'],b:'In lowering, out pressing.',alt:'Easier: assisted dip machine or bench dips. Harder: weight belt.'},
 /* ---------------- SHOULDERS ---------------- */
 shoulderpress:{n:'Seated dumbbell shoulder press',m:'Shoulders · triceps',eq:'Bench (upright) + dumbbells',fig:'shoulderpress',
  steps:['Sit on an upright bench, back supported.','Bring dumbbells to ear level, palms forward.','Press up until arms are almost straight, dumbbells close but not touching.','Lower slowly back to ear level.'],
  x:['Arching the lower back','Lowering too far','Elbows pointing straight forward'],b:'Out as you press.',alt:'Easier: shoulder press machine.'},
 machinepress:{n:'Shoulder press machine',m:'Shoulders · triceps',eq:'Shoulder press machine',fig:'shoulderpress',
  steps:['Adjust seat so handles start at shoulder height.','Back flat against the pad.','Press up smoothly until arms are almost straight.','Lower under control.'],
  x:['Seat too low','Lifting hips off the seat'],b:'Out as you press.',alt:'Next step: dumbbell shoulder press.'},
 ohp:{n:'Standing barbell overhead press',m:'Shoulders · triceps · core',eq:'Barbell',fig:'ohp',
  steps:['Bar on your front shoulders, hands just outside shoulder width.','Squeeze glutes and abs hard.','Press the bar straight up, moving your head back slightly to let it pass.','Lock out overhead with the bar over your mid-foot, head through.','Lower to the shoulders under control.'],
  x:['Leaning back','Pressing the bar forward instead of straight up','Loose core'],b:'Breathe in and brace before each rep, out at the top.',alt:'Easier: seated dumbbell press. Power version: push press with a small knee dip.'},
 lateral:{n:'Dumbbell lateral raise',m:'Side shoulders (width)',eq:'Light dumbbells',fig:'lateral',
  steps:['Stand tall, dumbbells at your sides, slight bend in the elbows.','Raise the dumbbells out to the sides up to shoulder height.','Lead with the elbows, pinkies slightly up.','Lower slowly over 2–3 seconds.'],
  x:['Swinging the body','Going too heavy','Shrugging'],b:'Out as you raise.',alt:'The most important exercise for wide Jin-Woo shoulders. Use light weight, perfect reps.'},
 frontraise:{n:'Dumbbell front raise',m:'Front shoulders',eq:'Light dumbbells',fig:'frontraise',
  steps:['Stand tall, dumbbells in front of your thighs.','Raise one or both arms straight forward to shoulder height.','Pause, then lower slowly.'],
  x:['Swinging','Raising above shoulder height'],b:'Out as you raise.',alt:'Light weight only. Pressing already trains the front shoulder.'},
 facepull:{n:'Face pull',m:'Rear shoulders · upper back',eq:'Cable + rope',fig:'facepull',
  steps:['Set the rope at head height. Grip with thumbs facing back.','Step back with arms straight.','Pull the rope toward your forehead, elbows high, hands moving apart.','Squeeze your rear shoulders, then return slowly.'],
  x:['Elbows dropping low','Leaning back to pull heavy weight'],b:'Out as you pull.',alt:'Protects your shoulders. Never skip it.'},
 revfly:{n:'Bent-over reverse fly',m:'Rear shoulders',eq:'Light dumbbells',fig:'revfly',
  steps:['Hinge forward with a flat back, dumbbells hanging below your chest.','Slight bend in the elbows.','Raise the dumbbells out to the sides, squeezing the shoulder blades.','Lower slowly.'],
  x:['Using momentum','Rounding the back'],b:'Out as you raise.',alt:'Alternative: rear-delt machine.'},
 shrug:{n:'Dumbbell shrug',m:'Traps',eq:'Dumbbells',fig:'shrug',
  steps:['Stand tall with heavy dumbbells at your sides.','Lift your shoulders straight up toward your ears.','Hold 1 second, then lower fully.'],
  x:['Rolling the shoulders','Bending the elbows'],b:'Out as you lift.',alt:'Barbell shrugs work too.'},
 /* ---------------- BACK & PULL ---------------- */
 pulldown:{n:'Lat pulldown, wide grip',m:'Lats (V-taper)',eq:'Lat pulldown machine',fig:'pulldown',
  steps:['Lock your knees under the pad. Grip the bar wider than your shoulders.','Lean back slightly, chest up.','Pull the bar to your upper chest by driving your elbows down and back.','Squeeze, then let the bar rise slowly to full stretch.'],
  x:['Pulling behind the neck with heavy weight','Swinging the body','Pulling with the arms instead of elbows'],b:'Out as you pull.',alt:'Builds toward bodyweight pull-ups.'},
 closepull:{n:'Close-grip lat pulldown',m:'Lats · mid back',eq:'Lat pulldown + V-handle',fig:'closepull',
  steps:['Attach the V-handle and sit with knees under the pad.','Lean back very slightly.','Pull the handle to your chest, elbows close to your body.','Return slowly to full stretch.'],
  x:['Leaning far back','Short range of motion'],b:'Out as you pull.',alt:'Alternative: neutral-grip pull-ups.'},
 pullup:{n:'Assisted pull-up',m:'Lats · biceps',eq:'Assisted pull-up machine or band',fig:'pullup',
  steps:['Set the assistance weight (more weight = more help).','Kneel on the pad and grip the bar slightly wider than shoulders.','Pull until your chin is over the bar.','Lower slowly to straight arms.'],
  x:['Half reps','Kicking'],b:'Out as you pull.',alt:'Reduce the assistance a little every week.'},
 pullbw:{n:'Pull-up',m:'Lats · biceps · core',eq:'Pull-up bar',fig:'pullbw',
  steps:['Hang from the bar, hands slightly wider than shoulders, palms forward.','Pull your shoulders down, then drive your elbows down to your sides.','Pull until your chin passes the bar.','Lower all the way to straight arms.'],
  x:['Kipping or swinging','Half reps','Shrugged shoulders at the bottom'],b:'Out as you pull, in as you lower.',alt:'Can\'t do one yet: jump up and lower slowly for 5 s (negatives). Harder: add weight with a belt.'},
 cablerow:{n:'Seated cable row',m:'Mid back · lats',eq:'Cable row machine',fig:'cablerow',
  steps:['Sit with feet on the platform, knees soft, back straight.','Grip the handle with arms straight.','Pull the handle to your belly, squeezing shoulder blades together.','Return slowly until arms are straight, without rounding.'],
  x:['Rocking the body back and forth','Rounding the back','Shrugging'],b:'Out as you pull.',alt:'Pause 1 s at the squeeze.'},
 bbrow:{n:'Barbell bent-over row',m:'Back thickness · lats',eq:'Barbell',fig:'bbrow',
  steps:['Hold the bar with an overhand grip, hinge to about 45° with a flat back.','Let the bar hang just below your knees.','Pull the bar to your belly button, elbows going back.','Lower under control.'],
  x:['Standing too upright','Jerking the weight','Rounded back'],b:'Out as you pull.',alt:'Easier: chest-supported dumbbell row.'},
 dbrow:{n:'Single-arm dumbbell row',m:'Lats · mid back',eq:'Bench + dumbbell',fig:'dbrow',
  steps:['Place one knee and the same hand on a bench, back flat.','Hold the dumbbell in the other hand, arm straight.','Pull the dumbbell to your hip, elbow close to your body.','Lower to full stretch. Do all reps, then switch sides.'],
  x:['Twisting the body','Pulling to the chest instead of the hip'],b:'Out as you pull.',alt:'Heavier is fine here as long as the back stays flat.'},
 /* ---------------- ARMS ---------------- */
 curl:{n:'Dumbbell or EZ-bar curl',m:'Biceps',eq:'Dumbbells or EZ bar',fig:'curl',
  steps:['Stand tall, arms straight, palms facing forward.','Keep elbows pinned to your sides.','Curl the weight up to shoulder level.','Lower over 2–3 seconds to straight arms.'],
  x:['Swinging the back','Elbows drifting forward','Fast lowering'],b:'Out as you curl.',alt:'Harder: incline dumbbell curl.'},
 hammer:{n:'Hammer curl',m:'Biceps · forearms',eq:'Dumbbells',fig:'hammer',
  steps:['Hold dumbbells with palms facing each other.','Elbows pinned at your sides.','Curl up to shoulder level, thumbs up.','Lower slowly.'],
  x:['Swinging','Elbows moving'],b:'Out as you curl.',alt:'Alternate arms if form breaks.'},
 pushdown:{n:'Rope pushdown',m:'Triceps',eq:'Cable + rope',fig:'pushdown',
  steps:['Grip the rope at chest height, elbows pinned to your sides.','Push the rope down until your arms are straight.','Spread the rope ends apart at the bottom and squeeze.','Let it rise slowly to chest height.'],
  x:['Elbows flaring','Leaning over the weight'],b:'Out as you push.',alt:'Alternative: straight bar.'},
 ohext:{n:'Overhead dumbbell extension',m:'Triceps (long head)',eq:'Dumbbell',fig:'ohext',
  steps:['Sit tall holding one dumbbell overhead with both hands.','Keep elbows pointing up, close to your head.','Lower the dumbbell behind your head until you feel a stretch.','Extend back up.'],
  x:['Elbows flaring wide','Arching the back'],b:'Out as you extend.',alt:'Alternative: overhead cable extension.'},
 skull:{n:'Skull crusher',m:'Triceps',eq:'EZ bar or dumbbells + bench',fig:'skull',
  steps:['Lie on a flat bench holding the weight over your chest, arms straight.','Keep upper arms still.','Bend the elbows to lower the weight toward your forehead or just behind your head.','Extend back up.'],
  x:['Upper arms moving','Going too heavy (hurts the elbows)'],b:'Out as you extend.',alt:'Easier: rope pushdown.'},
 /* ---------------- CORE ---------------- */
 kneeplank:{n:'Knee plank',m:'Core',eq:'Mat',fig:'kneeplank',
  steps:['Forearms on the floor, elbows under shoulders.','Knees down, body straight from head to knees.','Squeeze abs and glutes.','Hold, breathing normally.'],x:['Hips high','Holding the breath'],b:'Slow steady breathing.',alt:'Next: full plank.'},
 plank:{n:'Plank',m:'Core',eq:'Mat',fig:'plank',
  steps:['Forearms on the floor, elbows under shoulders.','Up on your toes, body straight from head to heels.','Squeeze glutes and pull the belly button in.','Hold without letting hips sag.'],x:['Hips sagging or piking','Looking forward'],b:'Slow steady breathing.',alt:'Harder: lift one foot.'},
 deadbug:{n:'Dead bug',m:'Deep core',eq:'Mat',fig:'deadbug',
  steps:['Lie on your back, arms pointing to the ceiling, knees bent 90° above hips.','Press your lower back into the floor.','Slowly extend the opposite arm and leg toward the floor.','Return and switch sides.'],x:['Lower back lifting','Moving fast'],b:'Breathe out as you extend.',alt:'Great for fixing belly posture.'},
 birddog:{n:'Bird dog',m:'Core · lower back',eq:'Mat',fig:'birddog',
  steps:['Start on hands and knees.','Reach your right arm forward and left leg back until both are straight.','Hold 2 seconds without twisting the hips.','Return and switch sides.'],x:['Twisting the hips','Arching the back'],b:'Out as you extend.',alt:'Harder: touch elbow to knee between reps.'},
 legraise:{n:'Lying leg raise',m:'Lower abs',eq:'Mat',fig:'legraise',
  steps:['Lie flat, hands under your hips.','Keep legs together and nearly straight.','Raise legs to vertical.','Lower slowly without letting your lower back arch.'],x:['Lower back arching','Dropping the legs fast'],b:'Out as you raise.',alt:'Easier: bent knees.'},
 hangknee:{n:'Hanging knee raise',m:'Lower abs · grip',eq:'Pull-up bar or captain\'s chair',fig:'hangknee',
  steps:['Hang from the bar with straight arms.','Stop any swinging.','Curl your knees up to chest height, tilting your pelvis up.','Lower slowly.'],x:['Swinging','Only lifting the knees to hip height'],b:'Out as you raise.',alt:'Easier: captain\'s chair. Harder: straight-leg raise.'},
 hangleg:{n:'Hanging leg raise',m:'Lower abs · hip flexors',eq:'Pull-up bar',fig:'hangleg',
  steps:['Hang still from the bar.','Keep legs straight and together.','Raise legs to at least hip height, ideally higher.','Lower slowly without swinging.'],x:['Swinging','Bending the knees to cheat'],b:'Out as you raise.',alt:'Easier: hanging knee raise.'},
 bicycle:{n:'Bicycle crunch',m:'Abs · obliques',eq:'Mat',fig:'bicycle',
  steps:['Lie on your back, hands lightly behind your head.','Lift your shoulders and legs off the floor.','Bring the right elbow toward the left knee while extending the right leg.','Switch sides slowly.'],x:['Pulling the neck','Rushing'],b:'Out on each twist.',alt:'Slow is harder and better.'},
 russian:{n:'Russian twist',m:'Obliques',eq:'Dumbbell or plate',fig:'russian',
  steps:['Sit with knees bent, lean back to about 45°.','Hold the weight at your chest.','Rotate your torso to bring the weight beside one hip, then the other.'],x:['Rounding the back','Moving only the arms'],b:'Out on each twist.',alt:'Easier: feet on the floor, no weight.'},
 situp:{n:'Sit-up',m:'Abs',eq:'Mat',fig:'situp',
  steps:['Lie on your back, knees bent, feet flat (hook them under something if needed).','Cross your arms on your chest.','Curl up to sitting.','Lower back down slowly.'],x:['Yanking with the neck','Dropping back down'],b:'Out as you sit up.',alt:'Part of the Daily Quest: 100 sit-ups.'},
 abwheel:{n:'Ab wheel rollout',m:'Core',eq:'Ab wheel + mat',fig:'abwheel',
  steps:['Kneel holding the ab wheel under your shoulders.','Brace the core and tuck the pelvis.','Roll forward slowly as far as you can without the lower back sagging.','Pull back with your abs.'],x:['Lower back sagging','Going too far too soon'],b:'In rolling out, out rolling back.',alt:'Easier: short range or roll toward a wall.'},
 cablecrunch:{n:'Kneeling cable crunch',m:'Abs',eq:'Cable + rope',fig:'cablecrunch',
  steps:['Kneel facing the cable, rope held beside your head.','Keep hips still.','Crunch down by curling your ribs toward your hips.','Return slowly.'],x:['Sitting back on the heels','Pulling with arms'],b:'Out as you crunch.',alt:'Abs need weight to grow and show.'},
 climber:{n:'Mountain climber',m:'Core · conditioning',eq:'None',fig:'climber',
  steps:['Start in a high push-up position.','Drive one knee toward your chest.','Switch legs quickly, like running in place.','Keep hips low and steady.'],x:['Hips bouncing high','Hands too far forward'],b:'Quick rhythmic breathing.',alt:'Easier: slow alternating steps.'},
 burpee:{n:'Burpee',m:'Full body · conditioning',eq:'None',fig:'burpee',
  steps:['Stand, then squat and place your hands on the floor.','Jump or step your feet back into a plank.','Optional push-up.','Jump feet back to your hands and stand or jump up.'],x:['Sagging hips in the plank','Landing heavy'],b:'Keep breathing. Do not hold.',alt:'Easier: step back instead of jumping.'},
 farmer:{n:'Farmer carry',m:'Grip · traps · core',eq:'Heavy dumbbells or kettlebells',fig:'farmer',
  steps:['Pick up heavy dumbbells with a flat back.','Stand tall, shoulders back.','Walk with short controlled steps for the distance or time.','Put the weights down by hinging, not rounding.'],x:['Leaning to one side','Shrugging'],b:'Steady breathing.',alt:'Builds real-world strength and grip.'},
 /* ---------------- CARDIO ---------------- */
 treadmill:{n:'Incline treadmill walk',m:'Cardio · fat loss',eq:'Treadmill',fig:'treadmill',
  steps:['Set incline 3–5 and speed 4.5–5 km/h.','Walk tall without holding the handrails.','Keep a pace where you can talk but not sing.'],x:['Holding the rails','Going too fast too soon'],b:'Steady nose or mouth breathing.',alt:'Raise incline before speed.'},
 intervals:{n:'Treadmill intervals',m:'Cardio',eq:'Treadmill',fig:'treadmill',
  steps:['Warm up for 5 minutes.','Alternate the fast and easy pace shown.','Keep good posture, no rails.'],x:['Skipping the warm-up'],b:'Recover your breathing in the easy parts.',alt:'Progress by adding 1 min fast per week.'},
 jogint:{n:'Walk-jog intervals',m:'Cardio',eq:'Treadmill or outdoors',fig:'jog',
  steps:['Walk briskly for 5 minutes.','Jog slowly, then walk, as shown.','You should be able to say a few words while jogging.'],x:['Jogging too fast'],b:'Relaxed rhythm: 3 steps in, 2 steps out.',alt:'Builds to continuous running.'},
 run:{n:'Steady run',m:'Cardio · endurance',eq:'Road or treadmill',fig:'jog',
  steps:['Start with 5 minutes easy.','Run at a conversational pace for the distance shown.','Short steps, land under your body.'],x:['Overstriding','Running every run hard'],b:'Rhythmic breathing.',alt:'Walk breaks are fine. Finishing matters more than speed.'},
 cycle:{n:'Stationary cycle',m:'Cardio',eq:'Bike',fig:'cycle',
  steps:['Seat at hip height, slight bend in the knee at the bottom.','Pedal at a steady moderate pace.'],x:['Seat too low'],b:'Steady breathing.',alt:'Low-impact cardio for recovery days.'},
 sprints:{n:'Cycle sprints',m:'Conditioning',eq:'Bike',fig:'cycle',
  steps:['Warm up 3 minutes easy.','Sprint hard for the fast part, pedal easy for the rest.','Repeat the rounds shown.'],x:['Resistance too low on sprints'],b:'Recover fully in the easy parts.',alt:'Burns fat in minimum time.'},
 jumprope:{n:'Jump rope',m:'Conditioning · calves',eq:'Skipping rope',fig:'jumprope',
  steps:['Hold the handles at hip height, elbows close.','Turn the rope with your wrists.','Jump just high enough to clear the rope, landing softly on the balls of your feet.'],x:['Jumping too high','Arms swinging wide'],b:'Relaxed steady breathing.',alt:'Do 30 s on, 30 s off to start.'},
 walk:{n:'Brisk walk',m:'Cardio · recovery',eq:'Outdoors',fig:'walk',
  steps:['Walk tall with arms swinging.','Pace where you can talk but not sing.'],x:['Strolling too slowly'],b:'Steady breathing.',alt:'Counts toward daily steps.'}
};
